ProDefExterna/SistemaVentaPrestamo/Controllers/PedidosController.cs
using SistemaVentaPrestamo.Models;
using SistemaVentaPrestamo.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace SistemaVentaPrestamo.Controllers
{
    [Authorize(Roles = "R1,R2")]
    public class PedidosController : Controller
    {
        BDDEFEXTEntities db = new BDDEFEXTEntities();
        // GET: Pedidos

        public ActionResult NuevoPedido()
        {
            var pedidoVista = new VistaPedido();
            pedidoVista.DerechoLinea = new DerechoLinea();
            pedidoVista.Encargado = new Personal();
            pedidoVista.Chofer = new Personal();
            pedidoVista.Repuestos = new List<OrdenRepuesto>();

            Session["pedidoVista"] = pedidoVista;

            var list = db.DerechoLinea.ToList();
            list.Add(new DerechoLinea { idDerechoLinea = 0, idDueño = "[seleccione un derecho de linea...]" });
            list = list.OrderBy(c => c.idDueño).ToList();
            ViewBag.idDerechoLinea = new SelectList(list, "idDerechoLinea", "idDueño");

            var list1 = db.Personal.ToList();
            list1.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Chofer...]" });
            list1 = list1.OrderBy(c => c.Login).ToList();
            ViewBag.idChofer = new SelectList(list1, "Login", "nombreCompleto");

            var list2 = db.Personal.ToList();
            list2.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Encargado...]" });
            list2 = list2.OrderBy(c => c.Login).ToList();
            ViewBag.idEncargado = new SelectList(list2, "Login", "nombreCompleto");


            return View(pedidoVista);
        }
        [HttpPost]
        public ActionResult NuevoPedido(VistaPedido pedidoVista)
        {
            pedidoVista = Session["pedidoVista"] as VistaPedido;

            var idDerechoLinea = int.Parse(Request["idDerechoLinea"]);
            var idChofer = Request["idChofer"].ToString();
            var idEncargado = Request["idEncargado"].ToString();

            if (idDerechoLinea == 0|| idChofer == "" || idEncargado == "")
            {
                var lista = db.DerechoLinea.ToList();
                lista.Add(new DerechoLinea { idDerechoLinea = 0, idDueño = "[seleccione un derecho de linea...]" });
                lista = lista.OrderBy(c => c.idDueño).ToList();
                ViewBag.idDerechoLinea = new SelectList(lista, "idDerechoLinea", "idDueño");
    

                var listb = db.Personal.ToList();
                listb.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Chofer...]" });
                listb = listb.OrderBy(c => c.Login).ToList();
                ViewBag.idChofer = new SelectList(listb, "Login", "nombreCompleto");


                var listc = db.Personal.ToList();
                listc.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Encargado...]" });
                listc = listc.OrderBy(c => c.Login).ToList();
                ViewBag.idEncargado = new SelectList(listc, "Login", "nombreCompleto");
                ViewBag.Error = "Debe Elegir un Encargado, Chofer y Derecho de Linea";

                return View(pedidoVista);
            }
            if (pedidoVista.Repuestos.Count == 0)
            {
                var lista = db.DerechoLinea.ToList();
                lista.Add(new DerechoLinea { idDerechoLinea = 0, idDueño = "[seleccione un derecho de linea...]" });
                lista = lista.OrderBy(c => c.idDueño).ToList();
                ViewBag.idDerechoLinea = new SelectList(lista, "idDerechoLinea", "idDueño");

                var listb = db.Personal.ToList();
                listb.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Chofer...]" });
                listb = listb.OrderBy(c => c.Login).ToList();
                ViewBag.idChofer = new SelectList(listb, "Login", "nombreCompleto");

                var listc = db.Personal.ToList();
                listc.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Encargado...]" });
                listc = listc.OrderBy(c => c.Login).ToList();
                ViewBag.idEncargado = new SelectList(listc, "Login", "nombreCompleto");
                ViewBag.Error = "Deben Elegir un Producto";

                return View(pedidoVista);
            }
            int prestamoID = 0;
            int cantRepuesto = 0;
            //Prueba de Transaccion
            int i = 0;

            using (var transaction = db.Database.BeginTransaction())
            //using (TransactionScope scope = new TransactionScope())
            {
                try
                {
                    DateTime fecLim = DateTime.Now.AddDays(3);
                    var prestamo = new Prestamo
                    {
                        idDerechoLinea = idDerechoLinea,
                        fechaInicio = DateTime.Now,
                        fechaLimite = fecLim,
                        idChofer = idChofer.ToString(),
                        idEncargado = idEncargado.ToString(),
                        Descripcion = Request["Descripcion"].ToString()
                    };
                    db.Prestamo.Add(prestamo);
                    db.SaveChanges();

                    prestamoID = db.Prestamo.ToList().Select(o => o.idPrestamo).Max();

                    foreach (var item in pedidoVista.Repuestos)
                    {
                        var detallePedido = new DetallePrestamo
                        {
                            idPrestamo = prestamoID,
                            idRepuesto = item.idRepuesto,
                            Cantidad = int.Parse(item.MontoCantidad.ToString()),
                            Estado = "Prestado"
                        };
                        cantRepuesto = db.Repuesto.Where(r => r.idRepuesto == detallePedido.idRepuesto).FirstOrDefault().Cantidad;
                        if (cantRepuesto - detallePedido.Cantidad <= 0)
                        {
                            transaction.Rollback();
                            ViewBag.Error = "Error: El repuesto pedido excede la cantidad de Inventario";

                            var listt1 = db.DerechoLinea.ToList();
                            listt1.Add(new DerechoLinea { idDerechoLinea = 0, idDueño = "[seleccione un derecho de linea...]" });
                            listt1 = listt1.OrderBy(c => c.idDueño).ToList();
                            ViewBag.idDerechoLinea = new SelectList(listt1, "idDerechoLinea", "idDueño");

                            var listt2 = db.Personal.ToList();
                            listt2.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Chofer...]" });
                            listt2 = listt2.OrderBy(c => c.Login).ToList();
                            ViewBag.idChofer = new SelectList(listt2, "Login", "nombreCompleto");

                            var listt3 = db.Personal.ToList();
                            listt3.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Encargado...]" });
                            listt3 = listt3.OrderBy(c => c.Login).ToList();
                            ViewBag.idEncargado = new SelectList(listt3, "Login", "nombreCompleto");

                            pedidoVista = new VistaPedido();
                            pedidoVista.DerechoLinea = new DerechoLinea();
                            pedidoVista.Encargado = new Personal();
                            pedidoVista.Chofer = new Personal();
                            pedidoVista.Repuestos = new List<OrdenRepuesto>();
                            Session["pedidoVista"] = pedidoVista;

                            return View(pedidoVista);
                        }
                        else
                        {

                            db.DetallePrestamo.Add(detallePedido);
                            db.SaveChanges();

                            //Prueba de Transaccion
                            //i++;
                            //if (i > 2)
                            //{
                            //  int a = 0;
                            //    i /= a;
                            //}
                        }
                    }
                    transaction.Commit();
                    //scope.Complete();
                    
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Error: " + ex.Message;
                    transaction.Rollback();
                    

                    var listt1 = db.DerechoLinea.ToList();
                    listt1.Add(new DerechoLinea { idDerechoLinea = 0, idDueño = "[seleccione un derecho de linea...]" });
                    listt1 = listt1.OrderBy(c => c.idDueño).ToList();
                    ViewBag.idDerechoLinea = new SelectList(listt1, "idDerechoLinea", "idDueño");

                    var listt2 = db.Personal.ToList();
                    listt2.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Chofer...]" });
                    listt2 = listt2.OrderBy(c => c.Login).ToList();
                    ViewBag.idChofer = new SelectList(listt2, "Login", "nombreCompleto");

                    var listt3 = db.Personal.ToList();
                    listt3.Add(new Personal { Login = "", nombreCompleto = "[seleccione un Encargado...]" });
                    listt3 = listt3.OrderBy(c => c.Login).ToList();
                    ViewBag.idEncargado = new SelectList(listt3, "Login", "nombreCompleto");


                    return View(pedidoVista);
                }
              
            }

            ViewBag.Message = string.Format("La orden: {0}, Grabada Exitosamente", prestamoID);

            var list = db.DerechoLinea.ToList();
            list.Add(new DerechoLinea { idDerechoLinea = 0, idDueño = "[seleccione un derecho de linea...]" });
            list = list.OrderBy(c => c.idDueño).ToList();

ProDefExterna/SistemaVentaPrestamo/Views/Pedidos/AddRepuesto.cshtml
@model SistemaVentaPrestamo.Models.OrdenRepuesto
@{ 
    ViewBag.Title = "Añadir Repuesto";
}

<h2>AddRepuesto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Prestamo</h4>
        <h3>@ViewBag.Error</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.idRepuesto, "Repuesto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idRepuesto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idRepuesto, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MontoCantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MontoCantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MontoCantidad, "", new { @class = "text-danger" })
            </div>
        </div>
             
        <input type="submit" value="Añadir Producto"  class="btn btn-default" />

    </div>
}

ProDefExterna/SistemaVentaPrestamo/Views/Pedidos/NuevoPedido.cshtml
@model SistemaVentaPrestamo.ViewModels.VistaPedido

@{
    ViewBag.Title = "NuevoPedido";
}

<h2>NuevoPedido</h2>
<h3>@ViewBag.Error</h3>
<h3>@ViewBag.Message</h3>

@using (Html.BeginForm("NuevoPedido","Pedidos",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Prestamo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.DerechoLinea.idDerechoLinea, "ID DerechoLinea", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idDerechoLinea", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DerechoLinea.idDerechoLinea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chofer.Login, "Login Chofer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idChofer", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Chofer.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Encargado.Login, "Login Encargado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEncargado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Encargado.Login, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaLimite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaLimite, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(model => model.fechaLimite, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @Html.ActionLink("Añadir Repuesto", "AddRepuesto", new { }, new { @class = "btn btn-primary" })
        <input type="submit" value="Guardar Pedido" id="NuevoPedido" class="btn btn-success" />

    </div>
}
<h2>Detalles Pedido</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrdenRepuesto.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrdenRepuesto.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrdenRepuesto.MontoCantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrdenRepuesto.Valor)
            </th>
            <th></th>
        </tr>

        @for (int i = 0; i < Model.Repuestos.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Repuestos[i].Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Repuestos[i].Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Repuestos[i].MontoCantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Repuestos[i].Valor)
                </td>
                <td>
                    @Html.ActionLink("Eliminar", "RemoveRepuesto", new { id = Model.Repuestos[i].idRepuesto })
                </td>
            </tr>
        }

    </table>


    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    @section scripts{
        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

        <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10",
                showOn: "both",
                buttonText : "Fecha"


            });
        })
        </script>
    }