ProDefExterna/SistemaVentaPrestamo/Controllers/ReportesController.cs
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaVentaPrestamo.Models;

namespace SistemaVentaPrestamo.Controllers
{
    [Authorize]
    public class ReportesController : Controller
    {
        BDDEFEXTEntities db = new BDDEFEXTEntities();

        // GET: Reportes
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Report1(Prestamo prestamo)
        {
            DateTime date1 = prestamo.fechaInicio;
            DateTime date2 = prestamo.fechaLimite;

            return RedirectToAction("ExportTo", new { ReportType = "PDF", fec1 = date1, fec2=date2 });
        }

        public FileResult ExportTo(string ReportType, DateTime fec1, DateTime fec2)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/Report1.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "ReportDataSet";
            reportDataSource.Value = db.View_Report1.ToList();

            localReport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=PrimerReporte." + fileNameExtension);

            return File(renderedBytes, fileNameExtension);

        }
        [HttpPost]
        public ActionResult Report2(string reportName)
        {
            return RedirectToAction("ExportTo2", new { ReportType = "PDF", nom = reportName });
        }

        public FileResult ExportTo2(string ReportType)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/Report2.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "ReportDataSet2";
            reportDataSource.Value = db.View_Report2.ToList();

            localReport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=SegundoReporte." + fileNameExtension);

            return File(renderedBytes, fileNameExtension);

        }
        [HttpPost]
        public ActionResult Report3(Prestamo prestamo)
        {
            DateTime date1 = prestamo.fechaInicio;
            DateTime date2 = prestamo.fechaLimite;
            return RedirectToAction("ExportTo3", new { ReportType = "PDF", fec1 = date1, fec2 = date2 });
        }

        public FileResult ExportTo3(string ReportType, DateTime fec1, DateTime fec2)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/Report3.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "ReportDataSet3";
            reportDataSource.Value = db.View_Report3.ToList();

            localReport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=TercerReporte." + fileNameExtension);

            return File(renderedBytes, fileNameExtension);

        }
        [HttpPost]
        public ActionResult Report4(int? reportName)
        {
            return RedirectToAction("ExportTo4", new { ReportType = "PDF", nom = reportName });
        }

        public FileResult ExportTo4(string ReportType)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/Report4.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "ReportDataSet4";
            reportDataSource.Value = db.View_Report4.OrderByDescending(x=>x.Stock).ToList();

            localReport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=CuartoReporte." + fileNameExtension);

            return File(renderedBytes, fileNameExtension);

        }
    }
}

ProDefExterna/SistemaVentaPrestamo/Views/Reportes/Index.cshtml
@model SistemaVentaPrestamo.Models.Prestamo

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Reportes</h2>

@using (Html.BeginForm("Report1", "Reportes", FormMethod.Post))
{

    <h4>Primer Reporte</h4>
    <hr />
    <p>Lista de fechas de cantidades de repuestos por tipo.</p>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "datepicker" } })             
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaLimite, new { htmlAttributes = new { @class = "datepicker" } })
            </div>
        </div>
    </div>
    <input type="submit" value="Generar Reporte" class="btn btn-default" />
    <hr />
}

@using (Html.BeginForm("Report2", "Reportes", FormMethod.Post))
{
    <h4>Segundo Reporte</h4>
    <hr />
    <p>Listado de interno que adeudan repuesto a la fecha.</p>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
               @* @Html.TextBox("reportName", null, new { @class = "form-control" })*@
                <input type="submit" value="Generar Reporte" class="btn btn-default" />
            </div>
        </div>
    </div>
    <hr />
}

@using (Html.BeginForm("Report3", "Reportes", FormMethod.Post))
{
    <h4>Tercer Reporte</h4>
    <hr />
    <p>Lista entre fechas de cantidades de repuestos vendidos por tipos y montos totales.</p>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "datepicker" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaLimite, new { htmlAttributes = new { @class = "datepicker" } })
            </div>
        </div>
    </div>
    <input type="submit" value="Generar Reporte" class="btn btn-default" />
    <hr />
}

@using (Html.BeginForm("Report4", "Reportes", FormMethod.Post))
{
    <h4>Cuarto Reporte</h4>
    <hr />
    <p>Listado de existencias en stock por tipo de repuestos ordenado en forma descendiente.</p>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @*@Html.TextBox("reportName", null, new { @class = "form-control" })*@
                <input type="submit" value="Generar Reporte" class="btn btn-default" />
            </div>
        </div>
    </div>
    <hr />
}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10",
                showOn: "both",
                buttonText : "Fecha"


            });
        })
    </script>
}